name: Hello World Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Worl
        run: echo "Hello World"
      - name: Bye 
        run: echo "Bye"
